cd p1-9101 && ../../src/redis-server redis.conf > redis.log &
cd p2-9102 && ../../src/redis-server redis.conf > redis.log &
cd p3-9103 && ../../src/redis-server redis.conf > redis.log &
cd r1-9201 && ../../src/redis-server redis.conf > redis.log &
cd r2-9202 && ../../src/redis-server redis.conf > redis.log &
cd r3-9203 && ../../src/redis-server redis.conf > redis.log &
cd read-r1-9301 && ../../src/redis-server redis.conf > redis.log &
cd read-r2-9302 && ../../src/redis-server redis.conf > redis.log &
cd read-r3-9303 && ../../src/redis-server redis.conf > redis.log &
